spring:
  application:
    name: sc-zuul

server:
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    sc-bs-ping: /ping/**
    sc-bs-pong: /pong/**
