spring:
  application:
    name: sc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: sc-bs-ping
        uri: lb://sc-bs-ping
        predicates:
        - Path=/ping/**

server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
